### ISSUE TITLE
Library can report incorrect error messages

### ISSUE THREAD

**Issue by svisser** [alecthomas/voluptuous#114]
Consider the following schema:

```python
s = Schema(
    Any(
        {Required('field'): In({'field_a', 'field_b'}), Required('value'): str},
        {Required('field'): In({'field_c', 'field_d'}), Required('value'): int},
    )
)
```

If I call `s({'field': 'field_a'})` I get:

- `voluptuous.MultipleInvalid: required key not provided @ data['value']`

If I call `s({'field': 'field_c'})` I get:

- `voluptuous.MultipleInvalid: value is not allowed for dictionary value @ data['field']`

The first of these makes sense, the second doesn't because `'field_c'` is a valid value for `'field'` in at least one alternative in `Any`.

This may be tricky to solve in the general case. When calling with ``s({'field': 'field_c'})` there are two errors for the first option (invalid "field" value and missing "value" field) and only one error for the second option (missing "value" field). So it may be possible to present the error message associated with the "least bad" match.

**Comment by alecthomas** [comment]
Yes, this can be confusing, however I don't believe there is a general purpose solution.

The second error does actually make sense if you think about the heuristic Voluptuous uses when reporting errors for `Any()`: It attempts to match each clause separately and reports the *first, deepest error that failed*. In your example, because both matches fail at a depth of 1, it uses the first error it found, which is the mismatch for `field` in the first clause.

When you use `Any()` with potentially large common sub-trees, how do you pick which failure is the correct one? Perhaps it might be possible to track which subtree has the most success and report the error from that branch. This would require a fairly non-trivial amount of work though, as each validator would need to report its successful matches. I'm not 100% sure the effort is worth the gain.

**Comment by svisser** [comment]
Yeah, I figured that this would be difficult to solve. I might be able to refactor the schema with more cases in `Any` which allows the right error message to be picked up. Feel free to close this issue - I mainly wanted to check whether small heuristic could be applied, I agree it's not worth restructuring the library for this.
