### ISSUE TITLE
Make error messages more useful by including the invalid value

### ISSUE THREAD

**Issue by thatneat** [alecthomas/voluptuous#140]
As a user, I want the built-in error messages to contain some information about the validation rule that was violated and the value that violated it, to shorten my debugging cycle.

currently, error messages are generally something like `voluptuous.MultipleInvalid: invalid list value @ data['top_level_key'][0]`. 
A better error message would be `voluptuous.MultipleInvalid: invalid list value @ data['top_level_key'][0]. Expected one of ['x', 'y', 'z'] but got 'Eyjafjallajökull'.`

This would make Voluptuous much more pleasant to work with.
There will of course be some cases where the rule/value isn't that simple, but they could be truncated/abbreviated in those cases.

**Comment by alecthomas** [comment]
The general approach I've taken with error messages is to be as minimal as possible. For more detailed messages, schema writers should provide explicit error messages. This is because in practice it's very difficult to give accurate error messages for non-trivial schemas. If Voluptuous tries to be too smart it can easily provide incorrect messages. Currently, the messages will almost always be "correct" because they're minimal.

Consider the following simplified (and nonsensical) example:

```python
s = Schema([{1: custom, {1: [2, 3, 4]}, {1: [5, 6, 7]}])
```

You can see that the error messages could quickly get out of hand. Add in custom validation functions, and you could easily end up with messages like `Expected one of {1: <function __main__.foo>}, {1: [2, 3, 4], {1: [5, 6, 7]}`.

So, yes, in theory I agree that error messages could be better, but the complexity of schemas, and the complexity of an implementation that could provide useful messages for those schemas is greater than simply asking schema authors to provide their own error messages. eg.

```python
s = Schema(Msg([1, 2, 3], msg='expected list containing 1, 2 or 3'))
```

You can checkout other discussion in #114, #127, and probably elsewhere.

**Comment by thatneat** [comment]
Nice, I didn't see `Msg()` in the docs. I definitely see how it could get unmanageable, but I think you could go a lot further before you've gone too far. I'm pushing for this because, in my use case at least, a schema validation failure *always* leads to someone trying to understand how to fix the problem. It seems like without too much work you could make that debugging process far easier in >50% of cases by leaning a *little* more towards too much information rather than too little.

There are two commonly missing pieces of information in the errors I've seen: the value that was provided, and the expected value.

For the first one, including the string representation of the invalid value would be plenty in most cases. `voluptuous.MultipleInvalid: invalid list value @ data['top_level_key'][0]` should become `voluptuous.MultipleInvalid: invalid list value 'foo' @ data['top_level_key'][0]`. fwiw I greatly appreciate the work that you've done to provide the path to the invalid data; that's something that most other libraries don't do. But in some cases the debugging will be quickest if you just do the obvious thing and repr the value.

As for conveying the rule that was broken, that's the place where I agree most that efforts could quickly become bulky and futile. However, even doing what you suggested above and truncating it at some number of characters you deem the maximum, eg. "`Expected one of {1: <function __main__.foo>}, {1: [2, 3, 4]}, <...truncated>`" would work quite well in a lot of cases.

**Comment by alecthomas** [comment]
I don't think I will add this feature but, that said, you should be able to do this yourself by using `Invalid.path`. It is basically what's used to construct the error messaage path.

**Comment by thatneat** [comment]
If I contributed a decent implementation as `voluptuous.humanize_error()` or `voluptuous.validate_with_humanized_error()`, would you accept a PR?
I'm at the point where I either need to factor my implementation out into its own package and use that everywhere I'm using voluptuous, or i could just contribute it here.

**Comment by tusharmakkar08** [comment]
Hey @thatneat , you can contribute it over here but make sure that it is backward compatible (otherwise it can break test cases written over `voluptuous` by some other application). You can pass an additional optional argument to the schema with `detailed_error_report_flag` and based on that create the `error_msg`

**Comment by alecthomas** [comment]
Agreed, I personally don't think it's that useful, but as an extra flag or wrapper function I think it would be fine.

**Comment by jaimemarijke** [comment]
Hi, do you have an estimated release date for the next version of volutptuous which will have this addition?
