### ISSUE TITLE
Python 3.6.1 - This QueryDict instance is immutable

### ISSUE THREAD

**Issue by vcorobceanu** [alecthomas/voluptuous#297]
In pyhon 3.6.1 i get error: 
AttributeError: This QueryDict instance is immutable

**Comment by tusharmakkar08** [comment]
Hey @vcorobceanu 

When do you get this error? When you are installing it? 

-TM

**Comment by vcorobceanu** [comment]
@tusharmakkar08 i get this error while validating request data:
https://image.prntscr.com/image/KmPveobJTzaNJWm6lkM0lA.png

**Comment by tusharmakkar08** [comment]
Hey @vcorobceanu 

Thanks for the description image. 

I can see that the issue is not due to Voluptuous but due to Django. You can read more about it over [here](https://stackoverflow.com/q/12611345/1799475). Currently, we only support mutable dict and not frozen dict/QueryDict. You need to convert the QueryDict to normal dictionary using something like [this](https://stackoverflow.com/a/13349753/1799475).

I guess this should solve the issue and hence closing it for now. Let me know if the issue is still unresolved. 

-TM
