### ISSUE TITLE
Python-2.6 support

### ISSUE THREAD

**Issue by abadger** [alecthomas/voluptuous#306]
Just feeling out the waters here.  Would you be willing to re-add support for Python-2.6?  I'm working on a project that needs to support RHEL-6 and CentOS-6 until they go EOL which means that this particular project needs to support Python-2.6 until November 2020.  I understand that not all projects are going to want to maintain support for older python versions for that long.  I figured I would never know what was possible until I asked.

**Comment by tusharmakkar08** [comment]
Hey @abadger 

Thanks for reaching out to us. 
We had purposefully removed Python-2.6 support since it isn't supported according to [dev guide](https://docs.python.org/devguide/#status-of-python-branches) it has been lifed out on 2013-10-29. I am therefore not sure to add additional maintenance effort for Python-2.6. 
Closing this issue.

Thanks.
