### ISSUE TITLE
Travis Failing Test Cases in Master

### ISSUE THREAD

**Issue by tusharmakkar08** [alecthomas/voluptuous#315]
Hey

Merging of PR: https://github.com/alecthomas/voluptuous/pull/311 has resulted in tests failure in the master branch. 

@dtao: Please look into this.

**Comment by dtao** [comment]
Yikes! I will take a look.

**Comment by dtao** [comment]
Hmm, so now that I'm looking into this I'm noticing that the issue seems to be that the `Schema.__eq__` method just tests for *string* equality of two objects' `schema` attributes. Since ordering of keys is not deterministic for `dict`s, I would argue this is actually a bug (i.e. if `a == Schema({'foo': 1, 'bar': 2})` and `b == Schema({'foo': 1, 'bar': 2})`, then `a == b` is non-deterministic). In which case the fix here is probably to fix the `__eq__` method to be deterministic for dict-based schemas.

@alecthomas Does that sound right to you? I am happy to create a PR to fix the issue.
