### ISSUE TITLE
No description at PyPI project page

### ISSUE THREAD

**Issue by mtelka** [alecthomas/voluptuous#474]
The PyPI project page at https://pypi.org/project/voluptuous/ is missing project description.  The page just says `No project description provided`.  I believe `voluptuous` deserves some description, for example `data validation library`.

**Comment by mtelka** [comment]
Sorry, the issue is still there and it is also visible on your screenshot.  Please look below "pip install voluptuous" and above "Navigation".

**Comment by bluefish6** [comment]
@mtelka I'm sorry, you're obviously right, I was mistaken due to "Project description" being written in the central part of the page :)

It seems that it's broken due to the fact that the long_description currently contains the `CONTRIBUTIONS ONLY` section (and an empty line at the beginning, which in fact is [set as the description](https://github.com/alecthomas/voluptuous/blob/master/setup.py#L11)).

I've created https://github.com/alecthomas/voluptuous/pull/477 to fix this and redeem my mistake :)
